### ISSUE TITLE
bug: "plan upgrade"

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/making-and-being-cms#6]
It says we've reached the maximum number of records .... ? can you explain or upgrade and I can venmo you? Or I can send my card info and it can do autopay--- depending on how much it costs let me know.
![image 1](https://user-images.githubusercontent.com/925548/48348285-eb0aef00-e64e-11e8-922c-2dd2b6b5db19.png)

**Comment by orzubalsky** [comment]
They changed their plan structure so we needed to reselect the free plan. I did that and it's working again. We can add up to 1000 records in the free plan.
